// Core n8n workflow types

export interface N8nWorkflow {
  name: string;
  nodes: N8nNode[];
  connections: N8nConnections;
  active?: boolean;
  settings?: {
    executionOrder?: 'v1' | 'v0';
    saveExecutionProgress?: boolean;
    saveManualExecutions?: boolean;
    saveDataErrorExecution?: 'all' | 'none';
    saveDataSuccessExecution?: 'all' | 'none';
    executionTimeout?: number;
    timezone?: string;
  };
  tags?: N8nTag[];
  meta?: Record<string, unknown>;
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  /**
   * Metadata generated by LLM (not sent to n8n API)
   * Used internally for preview and clarification
   */
  _meta?: WorkflowMeta;
}

/**
 * Workflow metadata for internal use
 * Generated by LLM, used for preview and clarification
 * NOT sent to n8n API
 */
export interface WorkflowMeta {
  assumptions?: string[];
  suggestions?: string[];
  requiresClarification?: string[];
}

export interface N8nNode {
  id?: string;
  name: string;
  type: string;
  typeVersion: number;
  position: [number, number];
  parameters: Record<string, unknown>;
  credentials?: Record<string, N8nCredentialReference>;
  disabled?: boolean;
  notes?: string;
  notesInFlow?: boolean;
  color?: string;
  continueOnFail?: boolean;
  executeOnce?: boolean;
  alwaysOutputData?: boolean;
  retryOnFail?: boolean;
  maxTries?: number;
  waitBetweenTries?: number;
  onError?: 'continueErrorOutput' | 'continueRegularOutput' | 'stopWorkflow';
}

export interface N8nCredentialReference {
  id: string;
  name: string;
}

export interface N8nConnections {
  [nodeName: string]: {
    [outputType: string]: Array<
      Array<{
        node: string;
        type: string;
        index: number;
      }>
    >;
  };
}

// n8n API response types

export interface N8nWorkflowResponse extends N8nWorkflow {
  id: string;
  createdAt: string;
  updatedAt: string;
  versionId: string;
}

export interface N8nCredential {
  id: string;
  name: string;
  type: string;
  data?: Record<string, unknown>;
  isResolvable?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface N8nCredentialSchema {
  type: 'object';
  additionalProperties: boolean;
  properties: Record<
    string,
    {
      type: string;
      displayName?: string;
      default?: unknown;
      required?: boolean;
      description?: string;
    }
  >;
  required?: string[];
}

export interface N8nExecution {
  id: string;
  finished: boolean;
  mode:
    | 'cli'
    | 'error'
    | 'integrated'
    | 'internal'
    | 'manual'
    | 'retry'
    | 'trigger'
    | 'webhook'
    | 'evaluation'
    | 'chat';
  retryOf?: string | null;
  retrySuccessId?: string | null;
  startedAt: string;
  stoppedAt?: string | null;
  workflowId: string;
  status: 'canceled' | 'crashed' | 'error' | 'new' | 'running' | 'success' | 'unknown' | 'waiting';
  waitTill?: string | null;
  customData?: Record<string, unknown>;
  data?: {
    resultData?: {
      runData?: Record<string, unknown[]>;
      lastNodeExecuted?: string;
      error?: {
        message: string;
        stack?: string;
      };
    };
    executionData?: {
      contextData?: Record<string, unknown>;
      nodeExecutionStack?: unknown[];
      waitingExecution?: Record<string, unknown>;
    };
  };
}

export interface N8nTag {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

// Node catalog types (from n8n-intelligence)

export interface NodeDefinition {
  name: string;
  displayName: string;
  description: string;
  icon?: string;
  iconUrl?: string;
  group: string[];
  version: number;
  subtitle?: string;
  defaults: {
    name: string;
    color?: string;
  };
  inputs: string[];
  outputs: string[];
  credentials?: Array<{
    name: string;
    required: boolean;
    displayOptions?: unknown;
  }>;
  properties: NodeProperty[];
  webhooks?: unknown[];
  polling?: boolean;
  triggerPanel?: unknown;
}

export interface NodeProperty {
  displayName: string;
  name: string;
  type: string;
  default: unknown;
  required?: boolean;
  description?: string;
  options?: Array<{
    name: string;
    value: string | number | boolean;
    description?: string;
  }>;
  displayOptions?: unknown;
  placeholder?: string;
  hint?: string;
  routing?: unknown;
}

export interface NodeSearchResult {
  node: NodeDefinition;
  score: number;
  matchReason: string;
}

// Workflow generation types

export interface KeywordExtractionResult {
  keywords: string[];
}

export interface WorkflowGenerationContext {
  prompt: string;
  keywords: string[];
  relevantNodes: NodeDefinition[];
  userId?: string;
}

/**
 * Result of semantic workflow matching
 */
export interface WorkflowMatchResult {
  matchedWorkflowId: string | null;
  confidence: 'high' | 'medium' | 'low' | 'none';
  matches: Array<{
    id: string;
    name: string;
    score: number;
  }>;
  reason: string;
}

export interface WorkflowValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
  fixedWorkflow?: N8nWorkflow;
}

// Credential management types (for cloud mode)

export interface UserTokens {
  accessToken: string;
  refreshToken?: string;
  expiresAt?: Date;
  expiresIn?: number;
  scope?: string;
  tokenType?: string;
  apiKey?: string; // For non-OAuth providers like Stripe
  domain?: string; // For providers like Freshdesk
  metadata?: Record<string, unknown>;
}

/**
 * Duck-typed OAuth service interface.
 * Any service with serviceType = "oauth" implementing these methods will work.
 * Used for cloud mode with automatic OAuth credential injection.
 */
export type OAuthService = {
  /**
   * Generate OAuth URL for user to authorize app connection
   */
  getAuthUrl(userId: string, provider: string, scopes: string[]): Promise<string>;

  /**
   * Check if user has connected a specific app
   */
  hasConnection(userId: string, credType: string): Promise<boolean>;

  /**
   * Get user's OAuth tokens for a credential type
   */
  getTokens(userId: string, credType: string): Promise<UserTokens | null>;

  /**
   * Get existing n8n credential ID for user + credential type
   */
  getN8nCredId(userId: string, credType: string): Promise<string | null>;

  /**
   * Store n8n credential ID after creation
   */
  setN8nCredId(userId: string, credType: string, credId: string): Promise<void>;

  /**
   * Get platform's OAuth app config (clientId, clientSecret) for a provider
   */
  getOAuthAppConfig?(provider: string): Promise<{
    clientId: string;
    clientSecret: string;
    scope?: string;
  }>;
};

/**
 * Type guard to check if a service implements OAuthService interface
 */
export function isOAuthService(service: unknown): service is OAuthService {
  if (!service || typeof service !== 'object') {
    return false;
  }

  const s = service as Record<string, unknown>;

  return (
    typeof s.getAuthUrl === 'function' &&
    typeof s.hasConnection === 'function' &&
    typeof s.getTokens === 'function' &&
    typeof s.getN8nCredId === 'function' &&
    typeof s.setN8nCredId === 'function'
  );
}

// Credential resolution types

export interface CredentialResolutionResult {
  workflow: N8nWorkflow;
  missingConnections: MissingConnection[];
  injectedCredentials: Map<string, string>; // credType -> n8nCredId
}

export interface MissingConnection {
  credType: string;
  oauthUrl?: string; // Only in cloud mode
}

// Plugin configuration types

export interface N8nPluginConfig {
  apiKey: string;
  host: string;
  credentials?: Record<string, string>; // credType -> n8nCredId (for local pre-configured mode)
}

// Action parameter types

export interface CreateWorkflowParams {
  prompt: string;
}

export interface WorkflowIdParams {
  workflowId: string;
}

export interface GetExecutionsParams {
  workflowId: string;
  limit?: number;
  status?: 'success' | 'error' | 'running' | 'waiting';
}

export interface WorkflowCreationResult extends Record<string, unknown> {
  id: string;
  name: string;
  active: boolean;
  nodeCount: number;
  missingCredentials: string[];
}

// Provider types

export interface WorkflowStatusInfo {
  id: string;
  name: string;
  active: boolean;
  lastExecution?: {
    id: string;
    status: string;
    startedAt: string;
    finishedAt?: string;
    error?: string;
  };
  tags: string[];
}

// Error types

export class N8nApiError extends Error {
  constructor(
    message: string,
    public statusCode?: number,
    public response?: unknown
  ) {
    super(message);
    this.name = 'N8nApiError';
  }
}

export class WorkflowValidationError extends Error {
  constructor(
    message: string,
    public errors: string[]
  ) {
    super(message);
    this.name = 'WorkflowValidationError';
  }
}

export class CredentialResolutionError extends Error {
  constructor(
    message: string,
    public missingConnections: MissingConnection[]
  ) {
    super(message);
    this.name = 'CredentialResolutionError';
  }
}
